#!/bin/bash

# Make sure we can develop

# Check if we have git
if ! which git >/dev/null; then
    echo "Missing git. "
    exit 1
fi

# Check we have node
if ! which node >/dev/null; then
    echo "Missing node. "
    exit 1
else
    echo -n "Node:  "
    node --version
fi

# Check we have jsdoc
if ! which jsdoc >/dev/null; then
    echo "Missing jsdoc. Install via: "
    echo "    npm install -g jsdoc"
    exit 1
else
    echo -n "JSDoc: "
    jsdoc --version
fi

echo "Checking submodules ..."
git submodule init
git submodule update

echo "Done. "
