#!/bin/bash

# Update the documentation.

ROOTDIR="$( cd "$( dirname "${BASH_SOURCE[0]}" )" && pwd )/../"
cd "$ROOTDIR"

# Remove old documentation.
rm -rf "$ROOTDIR/static/api"

echo -n "Generating documentation ..."
jsdoc -c "$ROOTDIR/jsdoc.json"
echo "Done. "
